### PR TITLE
fix panic behaivior when "cluster nodes" command shows other results than master and slave

### PR DESCRIPTION
**Pull request by hayashier**
In present implementation of redispipe, it expects master or slave as a result of "CLUSTER NODES", for example, following is result

```
$ redis-cli cluster nodes
6779c4a64f763756facc05fff3885a57147ad734 172.22.64.5:6379@1122 myself,master - 0 1581534729000 1 connected 0-16383
5ec5863c51da292b10b405cbf3334f5abfc3c89d 172.22.64.60:6379@1122 slave 6779c4a64f763756facc05fff3885a57147ad734 0 1581534812569 1 connected
```

But, actually there are other flags than "master" or "slave", for example, following is result. This situation could be caused by combination of gossip protocol of Redis Cluster and cache node replacement by ElastiCache.

```
$ redis-cli cluster nodes
6779c4a64f763756facc05fff3885a57147ad734 172.22.64.5:6379@1122 myself,master - 0 1581533572000 1 connected 0-16383
d600cae8b6a9c63852b7d0627e4409cb3df9b5f3 :6379@1122 handshake - 0 0 0 connected
5ec5863c51da292b10b405cbf3334f5abfc3c89d 172.22.64.60:6379@1122 slave 6779c4a64f763756facc05fff3885a57147ad734 0 1581533573911 1 connected
```

In present implementation, about whether slave or not is judged by the fact that ii.SlaveOf is empty or not. But above situation, it causes panic because the flag is handshake, not master nor slave.

So I fixed this problem.

### CODE REVIEW

**Comment by funny-falcon** [comment]
It is simpler to count "handshake" as a master: redis cluster can have "lonely masters" without slots.

I'll look at the patch today more closely today.

**Comment by funny-falcon** [comment]
Or even just ignore handshake, because it doesn't have IP address.

**Comment by funny-falcon** [comment]
Yeah, dud you try to just ignore handshake lines in CLUSTER NODES response?

**Comment by hayashier** [comment]
Thanks, Sokolov!

So do you mean that InstanceInfo include boolean property with name of Handshake instead of Master and Slave property?

```
ranges := make([]SlotsRange, 0, 16)
uuid2addrs := make(map[string][]string)
if ii.Handshake {
        return ranges
}
else {
        if ii.IsMaster() {
                uuid2addrs[ii.Uuid] = append([]string{ii.Addr}, uuid2addrs[ii.Uuid]...)
        } else {
                uuid2addrs[ii.SlaveOf] = append(uuid2addrs[ii.SlaveOf], ii.Addr)
        }
}
```

For present implementation of Redis, it seems to be good. I confirmed it works!

**Comment by funny-falcon** [comment]
No, I meant "Just skip lines in ParseClusterNodes".

**Comment by funny-falcon** [comment]
Could you please send me stacktrace of panic?
(Every bug repory should contain bug description as complete as possible)

**Comment by hayashier** [comment]
I understood. I understand I should add following code to ParseClusterNodes function such as follows. Is it right? In case of this issue, I think it's good.

```
if strings.Contains(parts[2], "handshake") {
        continue
}
```

Sorry now this issue was resolved and it's difficult to reproduce it. And I don't keep stacktrace.

**Comment by funny-falcon** [comment]
Yeah, it is right.

I think, real problem were in the absence of ip address:
`d600cae8b6a9c63852b7d0627e4409cb3df9b5f3 :6379@1122 handshake - 0 0 0 connected`

I'll put a commit with "handshake" check and "no-ip" check.

**Comment by funny-falcon** [comment]
I've pushed commit.
Thank you for report!!! :-)

It's pitty you didn't save stacktrace though :-(

**Pull request closed without merging**
